### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by roccomuso**
Want to merge improvements from @mildsunrise fork.
I'd love to add you as collaborator but I don't have admin permissions on the repo.
@mranney @jmaxxz @Subomi @skepticfx can you?

Closes:
https://github.com/node-pcap/node_pcap/pull/254
https://github.com/node-pcap/node_pcap/pull/225
https://github.com/node-pcap/node_pcap/pull/205
https://github.com/node-pcap/node_pcap/pull/219

### CODE REVIEW

**Comment by mildsunrise** [comment]
keep in mind `#1` refers to a pull request that was made on my fork :)

**Comment by roccomuso** [comment]
Ohh, github has linking conflicts.
Is that api change documented in the README?

**Comment by mildsunrise** [comment]
nope, radiotap decoder isn't documented so I made no mention of that

**Comment by roccomuso** [comment]
Ok I just need a list of PRs that this one will close. So I can clean the repo

**Comment by mildsunrise** [comment]
in addition to the ones you listed, this also includes PR #214 and #219
it also fixes #244 and #251 

if you want to merge this, I think it would be best to start a new major version (v3.0.0) and specify in `package.json` that only Node >= 10 is officially supported

**Comment by mildsunrise** [comment]
hmm, I'll prepare a reduced PR

**Pull request closed without merging**
