### PR TITLE
General improvements (reduced from #256)

### PR DESCRIPTION
**Pull request by mildsunrise**

### CODE REVIEW

**Comment by roccomuso** [comment]
Should be good for merge, can you confirm?

**Comment by mildsunrise** [comment]
I confirm :)

**Comment by roccomuso** [comment]
I'm gonna push a new release

**Comment by mildsunrise** [comment]
wait, before doing that... it would be good to document the new options and radiotap api

**Comment by roccomuso** [comment]
ok.
Also feel free to bump package.json version and then I'll publish

**Comment by mildsunrise** [comment]
and if we are going to release a major version, maybe it would be a good idea to change the `createSession` API to accept options instead of arguments, so you specify what you need:

~~~ js
pcap.createSession('eth0', {
    filter: '...',
    buffer_size: ...,
    monitor: ...,
    snap_length: ...,
    buffer_timeout: ...,
});

pcap.createOfflineSession('/path/to.pcap', {
    filter: '...',
});
~~~

**Comment by roccomuso** [comment]
let's change and document it.

**Pull request merged**
